const NOW = () => new Date();
export const partners = [
  {
    id: "partner1",
    name: "Gym Elite Tirana",
    slug: "gym-elite-tirana",
    mainImage: "/fitness/gym-elite.jpg",
    description:
      "Premium fitness center with modern equipment and professional trainers.",
    images: ["/fitness/gym-elite-1.jpg", "/fitness/gym-elite-2.jpg"],
    openTime: "06:00",
    closeTime: "23:00",
    dayOffs: ["Sunday"],
    address: "Rruga Dervish Hima",
    city: "Tirana",
    country: "Albania",
    thumbnailImage: "/fitness/gym-elite-thumb.jpg",
    longitude: 19.8187,
    latitude: 41.3275,
    phone: "+355 123 4567",
    website: "https://gymelite.al",
    isActive: true,
    deletedAt: null,
    createdAt: NOW(),
    updatedAt: NOW(),
  },
  {
    id: "partner2",
    name: "Wellness Spa Center",
    slug: "wellness-spa-center",
    mainImage: "/fitness/spa-center.jpg",
    description:
      "Relaxing spa with massage therapy, sauna, and wellness treatments.",
    images: ["/fitness/spa-1.jpg", "/fitness/spa-2.jpg"],
    openTime: "09:00",
    closeTime: "21:00",
    dayOffs: ["Sunday"],
    address: "Blloku Area",
    city: "Tirana",
    country: "Albania",
    thumbnailImage: "/fitness/spa-center-thumb.jpg",
    longitude: 19.819,
    latitude: 41.324,
    phone: "+355 234 5678",
    website: "https://wellnessspa.al",
    isActive: true,
    deletedAt: null,
    createdAt: NOW(),
    updatedAt: NOW(),
  },
  {
    id: "partner3",
    name: "Power Fitness Club",
    slug: "power-fitness-club",
    mainImage: "/fitness/power-fitness.jpg",
    description:
      "High-intensity training facility with CrossFit and weightlifting areas.",
    images: ["/fitness/power-1.jpg", "/fitness/power-2.jpg"],
    openTime: "05:30",
    closeTime: "22:30",
    dayOffs: [],
    address: "Rruga e Kavajes",
    city: "Tirana",
    country: "Albania",
    thumbnailImage: "/fitness/power-fitness-thumb.jpg",
    longitude: 19.813,
    latitude: 41.32,
    phone: "+355 345 6789",
    website: "https://powerfitness.al",
    isActive: true,
    deletedAt: null,
    createdAt: NOW(),
    updatedAt: NOW(),
  },
  {
    id: "partner4",
    name: "Aqua Sports Complex",
    slug: "aqua-sports-complex",
    mainImage: "/fitness/aqua-sports.jpg",
    description:
      "Swimming pool complex with aqua aerobics and swimming lessons.",
    images: ["/fitness/aqua-1.jpg", "/fitness/aqua-2.jpg"],
    openTime: "06:00",
    closeTime: "22:00",
    dayOffs: [],
    address: "Laguarezh",
    city: "Tirana",
    country: "Albania",
    thumbnailImage: "/fitness/aqua-sports-thumb.jpg",
    longitude: 19.81,
    latitude: 41.33,
    phone: "+355 456 7890",
    website: "https://aquasports.al",
    isActive: true,
    deletedAt: null,
    createdAt: NOW(),
    updatedAt: NOW(),
  },
  {
    id: "partner5",
    name: "Yoga & Meditation Studio",
    slug: "yoga-meditation-studio",
    mainImage: "/fitness/yoga-studio.jpg",
    description:
      "Peaceful studio for yoga classes, meditation, and mindfulness training.",
    images: ["/fitness/yoga-1.jpg", "/fitness/yoga-2.jpg"],
    openTime: "07:00",
    closeTime: "20:00",
    dayOffs: ["Sunday"],
    address: "Rruga Abdi Toptani",
    city: "Tirana",
    country: "Albania",
    thumbnailImage: "/fitness/yoga-studio-thumb.jpg",
    longitude: 19.817,
    latitude: 41.328,
    phone: "+355 567 8901",
    website: "https://yogastudio.al",
    isActive: true,
    deletedAt: null,
    createdAt: NOW(),
    updatedAt: NOW(),
  },
];
